### ISSUE TITLE
Can't delete plan

### ISSUE THREAD

**Issue by CoderTonyB** [MelbourneMakerSpace/Tonic#1]
Is this actually a bug or should we just hide the delete button?  When would we want to delete a plan?

**Comment by ramgarden** [comment]
We would edit a plan to change ots name or amount for sure. But we may want to delete plans in case we create a new one then decide we don't want it. Or a makerspace might decide to change from 5 plans to 3 for easier management?

**Comment by ramgarden** [comment]
Deleting a plan is dangerous! How best to handle the case where you delete a plan where there are 1 or more members set to use that plan? Don't allow it to delete then?  If it does delete then force the user to pick an existing plan to switch them all over to use in its place? If so then prorate everyone based on the fraction of the month based on each individuals start date?

**Comment by CoderTonyB** [comment]
I misspoke - I meant can we delete a plan once it was assigned to a member.  Since balance is now based on plan start/end times, we can't delete plans.  We need to remove the delete button or at least make it a cancel (close the screen) button instead.

**Comment by CoderTonyB** [comment]
old - done or no longer applicable
