### ISSUE TITLE
Need to be able to import from Seltzer DB

### ISSUE THREAD

**Issue by ramgarden** [MelbourneMakerSpace/Tonic#17]
Need a way to import all the members, keys and plan data from Seltzer DB.  The other option is to manually enter all the members and set their keys and plans one by one.  This can be done with a separate script or tool that can read from MySQL DB and Insert/Update to Firebase.
Here is a good example of using SQL to generate JSON that can then be used with Firebase IMPORT.
https://stackoverflow.com/questions/18916172/migrating-data-into-firebase-from-mysql

**Comment by ramgarden** [comment]
Should we still create this tool/script for use by 'spaces and orgs switching from Seltzer to Tonic?  Note that now that we have switched away from Firebase NoSQL to MySQL this is much easier to do.

**Comment by CoderTonyB** [comment]
old - done or no longer applicable
